apps/accounts/urls.py
from django.urls import path

from apps.accounts import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signin/", views.SignInView.as_view(), name="signin"),
    path("signout/", views.signout, name="signout"),
    path("user-create/", views.CreateUserView.as_view(), name="user-create"),
    path("users/", views.ListUserView.as_view(), name="user-list"),
    path("users-update/<int:id>/", views.UpdateUserView.as_view(), name="user-update"),
    path("users-delete/<int:id>/", views.DeleteUserView.as_view(), name="user-delete"),
]

apps/calendarapp/urls.py
from django.urls import path

from . import views

app_name = "calendarapp"


urlpatterns = [
    path("general-calendar", views.GeneralCalendar.as_view(), name="general-calendar"),
    path(
        "my-calendar-teacher/",
        views.MyCalendarTeacher.as_view(),
        name="my-calendar-teacher",
    ),
]

apps/reservation/urls.py
from django.urls import path
from .views import (
    CoordinatorGrantsReservationView,
    ReservationCreateView,
    ReservationDeleteView,
    ReservationListView,
    ReservationUpdateView,
    TeacherReservationListView,
)

app_name = "reservation"

urlpatterns = [
    path(
        "reservation-create/<int:id>",
        ReservationCreateView.as_view(),
        name="reservation-create",
    ),
    path(
        "teacher-reservation-list",
        TeacherReservationListView.as_view(),
        name="teacher-reservation-list",
    ),
    path("reservation-list", ReservationListView.as_view(), name="reservation-list"),
    path(
        "coordinator/reservation-grants/<int:id>",
        CoordinatorGrantsReservationView.as_view(),
        name="coordinator-reservation-feedback",
    ),
    path(
        "reservation-update/<int:id>",
        ReservationUpdateView.as_view(),
        name="reservation-update",
    ),
    path(
        "reservation-delete/<int:id>",
        ReservationDeleteView.as_view(),
        name="reservation-delete",
    ),
]

apps/rooms/urls.py
from django.urls import path
from .views import (
    RoomsToReservationListView,
    calendar_view,
    RoomsListView,
    RoomsCreateView,
    RoomsDeleteView,
    RoomsUpdateView,
)

app_name = "room"

urlpatterns = [
    path("calendar", calendar_view, name="calendar"),
    path(
        "reservation/room-list/",
        RoomsToReservationListView.as_view(),
        name="reservation-room-list",
    ),
    path("room-list", RoomsListView.as_view(), name="room-list"),
    path("room-create", RoomsCreateView.as_view(), name="room-create"),
    path("room-update/<int:id>", RoomsUpdateView.as_view(), name="room-update"),
    path("room-delete/<int:id>", RoomsDeleteView.as_view(), name="room-delete"),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from .views import DashboardView

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("admin/", admin.site.urls),
    path("accounts/", include("apps.accounts.urls")),
    path("", include("apps.calendarapp.urls")),
    path("rooms/", include("apps.rooms.urls")),
    path("reservation/", include("apps.reservation.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/dropdown_user.html
 <!-- User Menu-->
           <li class="dropdown">
            <a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu"><i class="fa fa-user fa-lg"></i></a>
            <ul class="dropdown-menu settings-menu dropdown-menu-right">
                <li>
                    <a class="dropdown-item" href="{% url 'accounts:signout' %}"><i class="fa fa-sign-out fa-lg" style="color: #198754"></i> Logout</a>
                </li>
            </ul>
        </li>

templates/partials/sidebar_menu.html
{% load static %}
<!-- Sidebar menu-->
 <div class="app-sidebar__overlay" data-toggle="sidebar"></div>
        
 <aside class="app-sidebar">
    <div class="app-sidebar-img">
        <a href="{% url 'dashboard' %}"><img class="app-sidebar__overlay" src="{% static 'images/logoifrooms.svg' %}" height="100px">
    </div></a>

    {% if request.user.is_superuser %}

     <ul class="app-menu">
        <li>
             <a class="app-menu__item active" href="{% url 'accounts:user-list' %}"><i class="app-menu__icon fa-solid fa-user"></i><span class="app-menu__label">Gerenciar Usuários</span></a>
         </li>
         <li class="app-sidebar__toggle_styles">
            <a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar">
                <i class="fa fa-up-right-and-down-left-from-center" style="color: #198754"></i>
            </a>
        </li>
     </ul>
     

    {% elif request.user.is_student %}
    
    <ul class="app-menu">
        <li>
             <a class="app-menu__item active" href="{% url 'calendarapp:general-calendar' %}"><i class="fa-solid fa-calendar-days"></i> <span class="app-menu__label "style="margin-left: 5px;">Calendário Geral</span></a>
         </li>
         <li class="app-sidebar__toggle_styles">
            <a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar">
                <i class="fa-solid fa-up-right-and-down-left-from-center" style="color: #198754;"></i>
            </a>
        </li>
     </ul>

     {% elif request.user.is_coordinator %}

     <ul class="app-menu">
        <li>
            <a class="app-menu__item{% if request.resolver_match.url_name == 'coord-grants' %} active{% endif %}" href="{% url 'reservation:reservation-list' %}">
                <i class="app-menu__icon fa fa-check-double"></i><span class="app-menu__label">Solicitações de Reserva</span>
            </a>
        </li>
        <li>
            <a class="app-menu__item{% if request.resolver_match.url_name == 'coord-rooms' %} active{% endif %}" href="{% url 'room:room-list' %}">
                <i class="app-menu__icon fa fa-list-check"></i><span class="app-menu__label">Gerenciar Salas</span>
            </a>
        </li>
        <li>
            <a class="app-menu__item{% if request.resolver_match.url_name == 'my-calendar-coordinator' %} active{% endif %}" href="{% url 'calendarapp:general-calendar' %}">
                <i class="fa-solid fa-calendar-days"></i> <span class="app-menu__label "style="margin-left: 5px;">Calendário Geral</span>
            </a>
        </li>
        <li class="app-sidebar__toggle_styles">
            <a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar">
                <i class="fa fa-up-right-and-down-left-from-center" style="color: #198754"></i>
            </a>
        </li>
    </ul>

     {% elif request.user.is_teacher %}

     <ul class="app-menu">
        <li>
            <a class="app-menu__item{% if request.resolver_match.url_name == 'booking-room' %} active{% endif %}" href="{% url 'room:reservation-room-list' %}">
                <i class="fa-solid fa-house-circle-check" ></i></i><span class="app-menu__label" style="margin-left: 5px;">Reservar</span>
            </a>
        </li>
        <li>
            <a class="app-menu__item{% if request.resolver_match.url_name == 'teacher-reservations' %} active{% endif %}" href="{% url 'reservation:teacher-reservation-list' %}">
                <i class="app-menu__icon fa fa-solid fa-book"></i><span class="app-menu__label">Minhas Reservas</span>
            </a>
        </li>
        <li>
            <a class="app-menu__item{% if request.resolver_match.url_name == 'my-calendar-teacher' %} active{% endif %}" href="{% url 'calendarapp:my-calendar-teacher' %}">
                <i class="fa-solid fa-calendar-days"></i> <span class="app-menu__label "style="margin-left: 5px;">Meu Calendário</span>
            </a>
        </li>
        <li class="app-sidebar__toggle_styles">
            <a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar">
                <i class="fa fa-up-right-and-down-left-from-center" style="color: #198754"></i>
            </a>
        </li>
    </ul>

     {% endif %}

 </aside>