apps/reservation/urls.py
from django.urls import path
from .views import (
    CoordinatorGrantsReservationView,
    ReservationCreateView,
    ReservationDeleteView,
    ReservationListView,
    ReservationUpdateView,
    TeacherReservationListView,
)

app_name = "reservation"

urlpatterns = [
    path(
        "reservation-create/<int:id>",
        ReservationCreateView.as_view(),
        name="reservation-create",
    ),
    path(
        "teacher-reservation-list",
        TeacherReservationListView.as_view(),
        name="teacher-reservation-list",
    ),
    path("reservation-list", ReservationListView.as_view(), name="reservation-list"),
    path(
        "coordinator/reservation-grants/<int:id>",
        CoordinatorGrantsReservationView.as_view(),
        name="coordinator-reservation-feedback",
    ),
    path(
        "reservation-update/<int:id>",
        ReservationUpdateView.as_view(),
        name="reservation-update",
    ),
    path(
        "reservation-delete/<int:id>",
        ReservationDeleteView.as_view(),
        name="reservation-delete",
    ),
]

apps/rooms/urls.py
from django.urls import path
from .views import (
    RoomsToReservationListView,
    calendar_view,
    RoomsListView,
    RoomsCreateView,
    RoomsDeleteView,
    RoomsUpdateView,
)

app_name = "room"

urlpatterns = [
    path("calendar", calendar_view, name="calendar"),
    path(
        "reservation/room-list/",
        RoomsToReservationListView.as_view(),
        name="reservation-room-list",
    ),
    path("room-list", RoomsListView.as_view(), name="room-list"),
    path("room-create", RoomsCreateView.as_view(), name="room-create"),
    path("room-update/<int:id>", RoomsUpdateView.as_view(), name="room-update"),
    path("room-delete/<int:id>", RoomsDeleteView.as_view(), name="room-delete"),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from .views import DashboardView

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("admin/", admin.site.urls),
    path("accounts/", include("apps.accounts.urls")),
    path("", include("apps.calendarapp.urls")),
    path("rooms/", include("apps.rooms.urls")),
    path("reservation/", include("apps.reservation.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/reservation/models.py
# models.py
from django.db import models
from apps.accounts.models import User
from apps.calendarapp.models import Event
from apps.rooms.models import Room
from datetime import datetime, time


class Reservation(models.Model):
    PERIODICITY_CHOICES = [
        ("daily", "Diária"),
        ("weekly", "Semanal"),
        ("monthly", "Mensal"),
    ]

    STATUS_CHOICES = [
        ("granted", "Deferido"),
        ("rejected", "Indeferido"),
        ("in_progress", "Aguardando Resposta"),
    ]

    date = models.DateField(verbose_name="Data:", blank=True, null=False)
    start_time = models.TimeField(verbose_name="Horário de Início")
    end_time = models.TimeField(verbose_name="Horário Final")
    justification = models.TextField(
        verbose_name="Justificativa:",
        max_length=200,
    )
    class_school = models.CharField(
        verbose_name="Turma:",
        max_length=50,
        blank=True,
        null=True,
    )
    periodicity = models.CharField(
        verbose_name="Periodicidade:",
        max_length=20,
        choices=PERIODICITY_CHOICES,
        blank=True,
        null=True,
    )
    annex = models.FileField(
        verbose_name="Anexo:", upload_to="reservation_annex/", blank=True, null=True
    )
    message = models.CharField(
        verbose_name="Mensagem ao Solicitante:", max_length=150, blank=True, null=True
    )
    reply = models.CharField(
        verbose_name="Mensagem ao Responsável:", max_length=150, blank=True, null=True
    )
    status = models.CharField(
        verbose_name="Status:",
        max_length=20,
        choices=STATUS_CHOICES,
    )
    id_room = models.ForeignKey(Room, on_delete=models.CASCADE, verbose_name="Sala")
    id_user_teacher = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="teacher_reservations",
        limit_choices_to={"registration_type": "teacher"},
        verbose_name="Professor",
    )

    def __str__(self):
        return f"Reservation {self.id} - {self.justification} - {self.date} {self.start_time}-{self.end_time}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        event = Event.objects.filter(id_reservation=self).first()

        if event:
            event.title = self.justification
            event.start = datetime.combine(self.date, self.convert_to_time(self.start_time))
            event.end = datetime.combine(self.date, self.convert_to_time(self.end_time))
            event.status = self.status
            event.save()
        else:
            Event.objects.create(
                user=self.id_user_teacher,
                title=self.justification,
                start=datetime.combine(self.date, self.convert_to_time(self.start_time)),
                end=datetime.combine(self.date, self.convert_to_time(self.end_time)),
                class_school=self.class_school,
                id_reservation=self,
                id_room=self.id_room,
                status=self.status,
            )

    def convert_to_time(self, input_time):
        if isinstance(input_time, time):
            return input_time

        return datetime.strptime(str(input_time), "%H:%M:%S").time()

apps/rooms/models.py
from django.db import models

from apps.accounts.models import User


class Room(models.Model):
    CHOICES_AVAILABLE = (
        ("yes", "Sim"),
        ("no", "Não"),
    )

    CHOICES_DEPARTMENT = (
        ("administration", "Bloco 01 - Direção"),
        ("main_building", "Bloco 02 - Principal"),
        ("laboratories", "Bloco 03 - Laboratórios"),
        ("dining_sector", "Bloco 04 - Setor de Alimentação"),
        ("library", "Bloco 05 - Biblioteca"),
        ("health_sector", "Bloco 06 - Setor de Saúde"),
        ("sports_gymnasium", "Bloco 07 - Ginásio Poliesportivo"),
        ("garage", "Bloco 08 - Garagem"),
        ("pool_and_field", "Bloco 09 - Piscina e Campo"),
        ("classrooms", "Bloco 10 - Salas de Aula"),
        ("honey_house", "Bloco 11 - Casa do Mel"),
        ("apiary", "Bloco 12 - Apiário"),
        ("vocational_training_center", "Bloco 13 - CVT"),
        ("campus_territory", "Território do Campus"),
    )

    room_name = models.CharField(
        max_length=100,
        verbose_name="Nome da Sala",
    )
    key = models.CharField(
        max_length=100,
        verbose_name="Chave da Sala",
    )
    department = models.CharField(
        max_length=100,
        verbose_name="Prédio:",
        choices=CHOICES_DEPARTMENT,
    )
    available = models.CharField(
        max_length=25,
        verbose_name="Agendável",
        choices=CHOICES_AVAILABLE,
    )
    id_user_coordinator = models.ManyToManyField(
        User,
        verbose_name="Avaliador de Agendamentos",
        related_name="coordinator_rooms",
        limit_choices_to={"registration_type": "coordinator"},
        blank=True,
        symmetrical=False,
    )

    def __str__(self):
        return self.room_name

apps/reservation/views.py
from django.utils import timezone
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.mixins import LoginRequiredMixin

from dateutil.relativedelta import relativedelta

from apps.reservation.form import (
    CoordinatorGrantsReservationForm,
    CreateReservationForm,
    UpdateReservationForm,
)
from apps.reservation.models import Reservation

from apps.rooms.models import Room
from apps.calendarapp.models import Event

from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)


class ReservationListView(ListView):
    model = Reservation
    template_name = "reservations/reservations.html"
    context_object_name = "reservations"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        filtered_reservations = Reservation.objects.filter(
            id_room__id_user_coordinator=self.request.user
        )

        context["reservations"] = filtered_reservations

        return context


class TeacherReservationListView(LoginRequiredMixin, ListView):
    model = Reservation
    template_name = "reservations/my_reservations.html"
    context_object_name = "reservations"

    def get_queryset(self):
        return Reservation.objects.filter(id_user_teacher=self.request.user)


class ReservationCreateView(CreateView):
    template_name = "reservations/form.html"
    form_class = CreateReservationForm
    success_url = reverse_lazy("dashboard")
    pk_url_kwarg = "id"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        room_id = self.kwargs.get(self.pk_url_kwarg)
        room = get_object_or_404(Room, id=room_id)
        context["room"] = room
        return context

    def form_valid(self, form):
        room = self.get_context_data().get("room")
        start_time = form.instance.start_time
        end_time = form.instance.end_time
        date = form.instance.date

        existing_reservations = Reservation.objects.filter(
            id_room=room,
            date=date,
            start_time__lt=end_time,
            end_time__gt=start_time,
        )

        if existing_reservations.exists():
            error_message = "Já existe uma reserva para este horário"
            return render(
                self.request, "reservations/form.html", {"error_message": error_message}
            )

        form.instance.id_room = room
        form.instance.id_user_teacher = self.request.user
        form.instance.status = "Aguardando Resposta"

        num_occurrences = form.cleaned_data.get("num_occurrences", 1)

        if form.instance.periodicity:
            for i in range(1, num_occurrences):
                new_date = self.calculate_new_date(
                    form.instance.date, form.instance.periodicity, i
                )

                new_reservation = Reservation(
                    date=new_date,
                    start_time=form.instance.start_time,
                    end_time=form.instance.end_time,
                    justification=form.instance.justification,
                    class_school=form.instance.class_school,
                    periodicity=form.instance.periodicity,
                    annex=form.instance.annex,
                    message=form.instance.message,
                    reply=form.instance.reply,
                    status=form.instance.status,
                    id_room=form.instance.id_room,
                    id_user_teacher=form.instance.id_user_teacher,
                )

                new_reservation.save()

        form.save()

        return super().form_valid(form)

    def calculate_new_date(self, base_date, periodicity, increment):
        if periodicity == "daily":
            return base_date + timezone.timedelta(days=increment)
        elif periodicity == "weekly":
            return base_date + timezone.timedelta(weeks=increment)
        elif periodicity == "monthly":
            return base_date + relativedelta(months=increment)


class CoordinatorGrantsReservationView(UpdateView):
    model = Reservation
    form_class = CoordinatorGrantsReservationForm
    template_name = "reservations/form_grants.html"
    pk_url_kwarg = "id"

    def form_valid(self, form):
        message = form.cleaned_data.get("message")

        if "deferir" in self.request.POST:
            form.instance.status = "Deferido"
        elif "indeferir" in self.request.POST:
            form.instance.status = "Indeferido"
        elif "enviar_feedback" in self.request.POST:
            form.instance.message = message
            form.instance.status = "Aguardando Resposta"

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("reservation:reservation-list")


class ReservationUpdateView(UpdateView):
    model = Reservation
    form_class = UpdateReservationForm
    template_name = "reservations/form_feedback.html"
    pk_url_kwarg = "id"
    success_url = reverse_lazy("reservation:reservation-list")

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        return self.render_to_response(
            self.get_context_data(form=form, reservation=self.object)
        )


class ReservationDeleteView(DeleteView):
    model = Reservation
    success_url = reverse_lazy("reservation:reservation-list")
    pk_url_kwarg = "id"

apps/reservation/views/form_grant_reservation.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

class GrantReservationFormView(LoginRequiredMixin, TemplateView):
    login_url = "accounts:signin"
    template_name = 'pages/coordinator/forms/form_grant_reservation.html'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['sua_variavel'] = 'Valor do contexto'
    #     context['outra_variavel'] = 'Outro valor do contexto'
    #     return context
    

apps/reservation/views/form_my_reservations.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

class MyReservationFormView(LoginRequiredMixin, TemplateView):
    login_url = "accounts:signin"
    template_name = 'pages/teacher/forms/form_my_reservation.html'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['sua_variavel'] = 'Valor do contexto'
    #     context['outra_variavel'] = 'Outro valor do contexto'
    #     return context
    

apps/reservation/views/form_room_reservation.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

class RoomReservationdFormView(LoginRequiredMixin, TemplateView):
    login_url = "accounts:signin"
    template_name = 'pages/teacher/forms/form_booking_room.html'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['sua_variavel'] = 'Valor do contexto'
    #     context['outra_variavel'] = 'Outro valor do contexto'
    #     return context
    

apps/reservation/views/grant_reservation.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

class GrantReservationFormView(LoginRequiredMixin, TemplateView):
    login_url = "accounts:signin"
    template_name = 'pages/coordinator/forms/grant_reservation.html'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['sua_variavel'] = 'Valor do contexto'
    #     context['outra_variavel'] = 'Outro valor do contexto'
    #     return context
    

apps/reservation/views/grants.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

class GrantsView(LoginRequiredMixin, TemplateView):
    login_url = "accounts:signin"
    template_name = 'pages/coordinator/grants.html'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['sua_variavel'] = 'Valor do contexto'
    #     context['outra_variavel'] = 'Outro valor do contexto'
    #     return context
    

apps/reservation/views/rooms.py
from django.views.generic import TemplateView

class RoomsView(TemplateView):
    template_name = 'pages/coordinator/rooms.html'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['sua_variavel'] = 'Valor do contexto'
    #     context['outra_variavel'] = 'Outro valor do contexto'
    #     return context
    

apps/reservation/views/teacher_form_my_reservations.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

# Minhas Reservas 

class TeacherMyReservationFormView(LoginRequiredMixin, TemplateView):
    login_url = "accounts:signin"
    template_name = 'pages/teacher/forms/form_my_reservation.html'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['sua_variavel'] = 'Valor do contexto'
    #     context['outra_variavel'] = 'Outro valor do contexto'
    #     return context
    

apps/rooms/views/my_reservations.py
from django.views.generic import TemplateView

class MyReservationView(TemplateView):
    template_name = 'pages/teacher/my_reservations.html'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['sua_variavel'] = 'Valor do contexto'
    #     context['outra_variavel'] = 'Outro valor do contexto'
    #     return context
    

apps/reservation/templates/reservations/my_reservations.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Minhas Reservas {% endblock title %}

{% block breadcrumb %}
    <div>
        <h1><i class="fa fa-list-check" style="color: #198754"></i> Minhas Reservas</h1>
    </div>
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}"><i class="fa fa-home fa-lg"></i></a></li>
        <li class="breadcrumb-item"><a href="{% url 'reservation:teacher-reservation-list' %}">Minhas Reservas</a></li>
        {% include 'partials/dropdown_user.html' %}
    </ul>
    
{% endblock breadcrumb %}

{% block content %}

<div class="table-responsive">
    <div id="sampleTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-hover table-bordered dataTable no-footer" id="sampleTable" role="grid" aria-describedby="sampleTable_info">
                    <thead>
                        <tr role="row">
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" >Ver Reserva</th>
                            <th class="sorting_asc" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-sort="ascending">Sala</th>
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" >Chave</th>
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" >Prédio</th>
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" >Justificativa</th>
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" >Data</th>
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" >Horário Início</th>
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" >Horário Fim</th>
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" >Situação</th>                            
                        </tr>
                    </thead>
                    <tbody>
                        {% for reservation in reservations %}
                            <tr role="row" class="odd">
                                    <td>
                                        {% if reservation.status == "Aguardando Resposta" %}
                                            <a href="{% url 'reservation:reservation-update' id=reservation.id %}"><i class="fas fa-search"></i></a>
                                        {% endif %}
                                    </td>
                                    <td>{{ reservation.id_room.room_name }}</td>
                                    <td>{{ reservation.id_room.key }}</td>
                                    <td>{{ reservation.id_room.get_department_display }}</td>
                                    <td>{{ reservation.justification }}</td>
                                    <td>{{ reservation.date|date:"d/m/Y" }}</td>
                                    <td>{{ reservation.start_time }}</td>
                                    <td>{{ reservation.end_time }}</td>
                                    <td>{{ reservation.status }}</td>
                                </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extrascripts %}
    <script type="text/javascript" src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/dataTables.bootstrap.min.js' %}"></script>
    <script type="text/javascript">$('#sampleTable').DataTable();</script>
{% endblock extrascripts %}

apps/reservation/templates/reservations/reservations.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Solicitações de Reserva {% endblock title %}

{% block breadcrumb %}
    <div>
        <h1><i class="fa fa-list-check" style="color: #198754"></i> Solicitações de Reserva</h1>
    </div>
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}"><i class="fa fa-home fa-lg"></i></a></li>
        <li class="breadcrumb-item"><a href="{% url 'reservation:reservation-list' %}"> Solicitações de Reserva</a></li>
        {% include 'partials/dropdown_user.html' %}
    </ul>
    
{% endblock breadcrumb %}

{% block content %}

<div class="table-responsive">
    <div id="sampleTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-hover table-bordered dataTable no-footer" id="sampleTable" role="grid" aria-describedby="sampleTable_info">
                    <thead>
                        <tr role="row">
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" >#</th>
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" >Data</th>
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" >De</th>
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" >Até</th>
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" >Justificativa</th>
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" >Periodicidade</th>
                            <th class="sorting_asc" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" >Professor</th>
                            <th class="sorting_asc" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" >Sala</th>
                            <th class="sorting_asc" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" >Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for reservation in reservations %}
                            <tr role="row" class="odd">
                                    <td>
                                        <a href="{% url 'reservation:coordinator-reservation-feedback' id=reservation.id %}"><i class="fas fa-search"></i></a>
                                    </td>
                                    <td>{{ reservation.date|date:"d/m/Y" }}</td>
                                    <td>{{ reservation.start_time }}</td>
                                    <td>{{ reservation.end_time }}</td>
                                    <td>{{ reservation.justification }}</td>
                                    <td>{% if reservation.periodicity %}
                                            {{ reservation.get_periodicity_display }}
                                        {% else %}
                                            Nenhuma
                                        {% endif %}
                                    </td>
                                    <td>{{ reservation.id_user_teacher }}</td>
                                    <td>{{ reservation.id_room }}</td>
                                    <td>{{ reservation.status }}</td>
                                </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extrascripts %}
    <script type="text/javascript" src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/dataTables.bootstrap.min.js' %}"></script>
    <script type="text/javascript">$('#sampleTable').DataTable();</script>
{% endblock extrascripts %}

apps/reservation/templates/reservations/rooms-to-reservation.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Reservar Sala {% endblock title %}

{% block breadcrumb %}
    <div>
        <h1><i class="fa fa-list-check" style="color: #198754"></i> Reservar Sala</h1>
    </div>
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}"><i class="fa fa-home fa-lg"></i></a></li>
        <li class="breadcrumb-item"><a href="{% url 'room:reservation-room-list' %}">Reservar</a></li>
        {% include 'partials/dropdown_user.html' %}
    </ul>
    
{% endblock breadcrumb %}

{% block content %}

<div class="table-responsive">
    <div id="sampleTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-hover table-bordered dataTable no-footer" id="sampleTable" role="grid" aria-describedby="sampleTable_info">
                    <thead>
                        <tr role="row">
                            <th class="sorting_asc" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 261.641px;">Reservar</th>
                            <th class="sorting_asc" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 261.641px;">Nome</th>
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 417.312px;">Chave</th>
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 189.281px;">Prédio</th>
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 189.281px;">Agendável</th>
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 102.141px;">Responsável</th>
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 102.141px;">Agendamentos</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for room in rooms %}
                                <tr role="row" class="odd">
                                    {% if room.get_available_display == "Sim" and room.id_user_coordinator.all %}
                                        <td><a href="{% url 'reservation:reservation-create' id=room.id %}"><i class="fa-solid fa-building-circle-arrow-right"></i></a></td>
                                    {% else %}
                                    <td></td>
                                    {% endif %}
                                    <td> {{ room.room_name }}</td>
                                    <td>{{ room.key }}</td>
                                    <td>{{ room.get_department_display }}</td>
                                    <td>{{ room.get_available_display }}</td>
                                    <td>
                                        {% for coordinator in room.id_user_coordinator.all %}
                                            {{ coordinator.name }}
                                            {% if not forloop.last %}, {% endif %}
                                        {% endfor %}
                                    </td>
                                    <td>
                                        <a href="{% url 'room:calendar' %}">
                                            <i class="fa fa-calendar-days" style="color: #198754;"></i>
                                        </a>
                                    </td>
                                </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extrascripts %}
    <script type="text/javascript" src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/dataTables.bootstrap.min.js' %}"></script>
    <script type="text/javascript">$('#sampleTable').DataTable();</script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
{% endblock extrascripts %}