apps/accounts/urls.py
from django.urls import path

from apps.accounts import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signin/", views.SignInView.as_view(), name="signin"),
    path("signout/", views.signout, name="signout"),
    path("user-create/", views.CreateUserView.as_view(), name="user-create"),
    path("users/", views.ListUserView.as_view(), name="user-list"),
    path("users-update/<int:id>/", views.UpdateUserView.as_view(), name="user-update"),
    path("users-delete/<int:id>/", views.DeleteUserView.as_view(), name="user-delete"),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from .views import DashboardView

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("admin/", admin.site.urls),
    path("accounts/", include("apps.accounts.urls")),
    path("", include("apps.calendarapp.urls")),
    path("rooms/", include("apps.rooms.urls")),
    path("reservation/", include("apps.reservation.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    def _create_user(
        self, registration, password=None, registration_type="student", **extra_fields
    ):
        user = self.model(
            registration=registration,
            registration_type=registration_type,
            **extra_fields,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_student(
        self, registration, password=None, registration_type="student", **extra_fields
    ):
        extra_fields.setdefault("is_student", True)
        return self._create_user(
            registration, password, registration_type, **extra_fields
        )

    def create_teacher(
        self, registration, password=None, registration_type="teacher", **extra_fields
    ):
        extra_fields.setdefault("is_teacher", True)
        return self._create_user(
            registration, password, registration_type, **extra_fields
        )

    def create_coordinator(
        self,
        registration,
        password=None,
        registration_type="coordinator",
        **extra_fields,
    ):
        extra_fields.setdefault("is_coordinator", True)
        return self._create_user(
            registration, password, registration_type, **extra_fields
        )

    def create_superuser(self, registration, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        return self._create_user(registration, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """Custom user model"""

    REGISTRATION_TYPE_CHOICES = [
        ("student", _("Aluno")),
        ("coordinator", _("Coordenador")),
        ("teacher", _("Professor")),
    ]

    registration = models.CharField(
        _("Matrícula"),
        max_length=12,
        unique=True,
        help_text="Ex: 123456",
    )

    name = models.CharField(_("Nome"), max_length=100)

    email = models.EmailField(_("E-mail"), unique=True)

    registration_type = models.CharField(
        _("Tipo"),
        max_length=20,
        choices=REGISTRATION_TYPE_CHOICES,
        default="student",
    )

    is_superuser = models.BooleanField(_("Superuser"), default=False)
    is_staff = models.BooleanField(_("Staff"), default=False)
    is_active = models.BooleanField(_("Active"), default=True)
    is_student = models.BooleanField(_("Student"), default=True)
    is_coordinator = models.BooleanField(_("Coordinator"), default=False)
    is_teacher = models.BooleanField(_("Teacher"), default=False)
    date_joined = models.DateTimeField(_("Date Joined"), auto_now_add=True)
    last_updated = models.DateTimeField(_("Last Updated"), auto_now=True)

    objects = UserManager()

    USERNAME_FIELD = "registration"

    def save(self, *args, **kwargs):
        if self.registration_type == "student":
            self.is_student = True
            self.is_coordinator = False
            self.is_teacher = False
        elif self.registration_type == "coordinator":
            self.is_student = False
            self.is_coordinator = True
            self.is_teacher = False
        elif self.registration_type == "teacher":
            self.is_student = False
            self.is_coordinator = False
            self.is_teacher = True

        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.name} ({self.registration})"

apps/accounts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.password_validation import validate_password

from apps.accounts.models import User


class SignInForm(forms.Form):
    registration = forms.CharField(
        label="Matrícula", widget=forms.TextInput(attrs={"class": "form-control"})
    )
    password = forms.CharField(
        label="Senha", widget=forms.PasswordInput(attrs={"class": "form-control"})
    )
    error_message = None


class SignUpForm(forms.ModelForm):
    name = forms.CharField(
        label="name",
        widget=forms.TextInput(attrs={"class": "form-control"}),
        max_length=100,
        required=True,
    )
    email = forms.EmailField(
        label="E-mail",
        widget=forms.EmailInput(attrs={"class": "form-control"}),
        required=True,
    )
    registration = forms.CharField(
        label="Matrícula",
        widget=forms.TextInput(attrs={"class": "form-control"}),
        max_length=12,
        required=True,
        help_text="Máximo de 12 caracteres",
    )
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
        validators=[validate_password],
    )
    password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
        validators=[validate_password],
    )

    class Meta:
        model = User
        fields = ["name", "email", "registration"]

    def clean_registration(self):
        registration = self.cleaned_data.get("registration")
        if len(registration) > 12:
            raise forms.ValidationError(
                "A matrícula não pode ter mais de 12 caracteres."
            )
        return registration

    def clean_password2(self):
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Senhas não conferem!")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name', 'email', 'registration', 'registration_type']
        
        labels = {
            'name': ('Nome'),
            'email': ('E-mail'),
            'registration': ('Matrícula'),
            'registration_type': ('Função'),
        }
        
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'registration': forms.TextInput(attrs={'class': 'form-control'}),
            'registration_type': forms.Select(attrs={'class': 'form-control'}),
        }
        
        help_texts = {
            'registration': 'Máximo de 12 caracteres',
        }
  

apps/accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic import View
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login

from apps.accounts.forms import SignInForm, UpdateUserForm

from django.contrib.auth import logout

from apps.accounts.forms import SignUpForm

from django.views.generic import (
    UpdateView,
    ListView,
    DeleteView,
    TemplateView,
)
from django.contrib.auth.mixins import LoginRequiredMixin

from apps.accounts.models import User


class UsersView(LoginRequiredMixin, TemplateView):
    login_url = "accounts:signin"
    template_name = "pages/admin/users.html"


class SignUpView(View):
    """User registration view"""

    template_name = "accounts/signup.html"
    form_class = SignUpForm

    def get(self, request, *args, **kwargs):
        forms = self.form_class()
        context = {"form": forms}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        forms = self.form_class(request.POST)
        if forms.is_valid():
            forms.save()
            return redirect("accounts:signin")
        context = {"form": forms}
        return render(request, self.template_name, context)


def signout(request):
    logout(request)
    return redirect("accounts:signin")


class SignInView(View):
    """User registration view"""

    template_name = "accounts/signin.html"
    form_class = SignInForm

    def get(self, request, *args, **kwargs):
        forms = self.form_class()
        context = {"form": forms}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        forms = self.form_class(request.POST)
        if forms.is_valid():
            registration = forms.cleaned_data["registration"]
            password = forms.cleaned_data["password"]
            user = authenticate(registration=registration, password=password)
            if user:
                login(request, user)
                return redirect("dashboard")
            else:
                forms.error_message = (
                    "Credenciais inválidas. Verifique sua matrícula e senha."
                )
        context = {"form": forms}
        return render(request, self.template_name, context)


class CreateUserView(LoginRequiredMixin, TemplateView):
    login_url = "accounts:signin"
    template_name = "pages/admin/forms/form_create_user.html"


class ListUserView(ListView):
    model = User
    template_name = "accounts/users.html"
    context_object_name = "users"


class UpdateUserView(UpdateView):
    model = User
    form_class = UpdateUserForm
    template_name = "accounts/form.html"
    success_url = reverse_lazy("accounts:user-list")
    pk_url_kwarg = "id"


class DeleteUserView(DeleteView):
    model = User
    pk_url_kwarg = "id"
    template_name = "accounts/user_confirm_delete.html"
    success_url = reverse_lazy("accounts:user-list")

apps/accounts/templates/accounts/form.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Usuário {% endblock title %}

{% block breadcrumb %}
    <div>
        <h1><i class="fa-solid fa-user" style="color: #198754"></i> Usuário</h1>
    </div>
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}"><i class="fa fa-home fa-lg"></i></a></li>
        <li class="breadcrumb-item"><a href="{% url 'accounts:user-list' %}">Gerenciar Usuários</a></li>
        <li class="breadcrumb-item"><a href="#">Usuário</a></li>
        {% include 'partials/dropdown_user.html' %}
    </ul>
    
{% endblock breadcrumb %}

{% block content %}
<div class="row container">

    <form class="col-md-6" method="post" enctype="multipart/form-data">

        {% csrf_token %}
        {{ form.as_p }}
        <a class="btn btn-secondary" href="{% url 'accounts:user-list' %}">Descartar</a>
        <button type="submit" class="btn btn-success">Salvar</button>
    </form>
</div>

{% endblock %}

apps/accounts/templates/accounts/user_confirm_delete.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Usuário {% endblock title %}

{% block breadcrumb %}
    <div>
        <h1><i class="fa-solid fa-user" style="color: #198754"></i> Usuário</h1>
    </div>
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}"><i class="fa fa-home fa-lg"></i></a></li>
        <li class="breadcrumb-item"><a href="{% url 'accounts:user-list' %}">Gerenciar Usuários</a></li>
        <li class="breadcrumb-item"><a href="#">Confirmar exclusão</a></li>
        {% include 'partials/dropdown_user.html' %}
    </ul>
    
{% endblock breadcrumb %}

{% block content %}
<div class="table-responsive">

    <form method="post">{% csrf_token %}
        <p>Confirmar a exclusão de "{{ object }}"?</p>
        {{ form }}
        <div style="display: flex; gap:10px; align-items: center;">
            <button type="button" class="btn btn-secondary" onclick="redirectToUserList()">Cancelar</button>
            <input type="submit" class="btn btn-danger" value="Confirmar">
          </div>
    </form>
    
</div>

<script>
    function redirectToUserList() {
        window.location.href = '{% url "accounts:user-list" %}';
    }
</script>
{% endblock %}

apps/accounts/templates/accounts/users.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Gerenciar Usuários{% endblock title %}

{% block breadcrumb %}
    <div>
        <h1><i class="fa-solid fa-user" style="color: #198754"></i> Gerenciar Usuários</h1>
    </div>
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}"><i class="fa fa-home fa-lg"></i></a></li>
        <li class="breadcrumb-item"><a href="{% url 'accounts:user-list' %}">Gerenciar Usuários</a></li>
        {% include 'partials/dropdown_user.html' %}
    </ul>
    
{% endblock breadcrumb %}

{% block content %}

<div class="table-responsive">
    <div id="sampleTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-hover table-bordered dataTable no-footer" id="sampleTable" role="grid" aria-describedby="sampleTable_info">
                    <thead>
                        <tr role="row">
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 102.141px;">#</th>
                            <th class="sorting_asc" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 261.641px;">Nome</th>
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 417.312px;">Matrícula</th>
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 189.281px;">Função</th>
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 189.281px;">E-mail</th>
                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 189.281px;"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in users %}
                                <tr role="row">
                                    <td> <a href="{% url 'accounts:user-update' id=user.id %}"><i class="fas fa-search"></i></a></td>
                                    <td>{{ user.name }}</td>
                                    <td>{{ user.registration }}</td>
                                    <td>{{ user.get_registration_type_display }}</td>
                                    <td>{{ user.email }}</td>
                                    <td>
                                        <a href="{% url 'accounts:user-delete' id=user.id %}">
                                            <i class="fa-solid fa-trash" style="color:  #198754;"></i>
                                        </a>
                                    </td>
                                </tr>
                        {% endfor %} 
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extrascripts %}
    <script type="text/javascript" src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/dataTables.bootstrap.min.js' %}"></script>
    <script type="text/javascript">$('#sampleTable').DataTable();</script>
{% endblock extrascripts %}